# Generated by Django 5.0.2 on 2024-05-25 07:47

import autoslug.fields
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='user', unique=True)),
                ('tempid', models.UUIDField(default=uuid.uuid4)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='phone number')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone number')),
                ('state', models.CharField(max_length=50, verbose_name='state')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('block', models.PositiveSmallIntegerField(verbose_name='block')),
                ('street', models.CharField(max_length=50, verbose_name='street')),
                ('road', models.CharField(blank=True, max_length=30, null=True, verbose_name='road')),
                ('building', models.CharField(max_length=30, verbose_name='building')),
                ('floor', models.PositiveSmallIntegerField(null=True, verbose_name='floor')),
                ('apartment', models.PositiveSmallIntegerField(verbose_name='apartment')),
                ('address_description', models.TextField(blank=True, null=True, verbose_name='address description')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='customer.customer')),
            ],
        ),
    ]
