# Generated by Django 5.0.2 on 2024-05-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_id_alter_customer_tempid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='tempid',
            new_name='id',
        ),
    ]
