# Generated by Django 5.0.2 on 2024-05-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_tempid_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='id',
            new_name='uuid',
        ),
    ]
