# Generated by Django 5.0.2 on 2024-05-25 08:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_id_customer_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='uuid',
        ),
        migrations.AddField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, default='123456789', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='uuid4',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
