# Generated by Django 5.0.2 on 2024-05-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_customer_uuid_customer_id_customer_uuid4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='uuid4',
        ),
    ]
