# Generated by Django 5.0.2 on 2024-05-25 08:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_customer_uuid4'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='uuid4',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
