# Generated by Django 5.0.2 on 2024-05-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customer_uuid4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='uuid4',
            new_name='uuid',
        ),
    ]
