# Generated by Django 4.2.8 on 2024-01-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menucategory_name_alter_menucategory_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='image'),
        ),
    ]
