# Generated by Django 4.2.8 on 2024-01-18 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_itemoption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemoption',
            old_name='mneu_item',
            new_name='menu_item',
        ),
        migrations.AlterField(
            model_name='itemoption',
            name='crust',
            field=models.CharField(blank=True, max_length=20, verbose_name='crust'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price'),
        ),
    ]
