# Generated by Django 4.2.8 on 2024-01-27 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_rename_mneu_item_itemoption_menu_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemoption',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_option', to='menu.menuitem'),
        ),
    ]
