# Generated by Django 4.2.8 on 2024-02-03 16:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_itemoption_menu_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30, unique=True, verbose_name='value')),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
            ],
        ),
        migrations.RemoveField(
            model_name='itemoption',
            name='crust',
        ),
        migrations.RemoveField(
            model_name='itemoption',
            name='price',
        ),
        migrations.RemoveField(
            model_name='itemoption',
            name='size',
        ),
        migrations.AddField(
            model_name='itemoption',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='itemoption',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='itemoption',
            name='value',
            field=models.ManyToManyField(to='menu.optionfieldvalue', verbose_name='value'),
        ),
    ]
