# Generated by Django 4.2.8 on 2024-02-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_optionfieldvalue_remove_itemoption_crust_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionfieldvalue',
            name='value',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='value'),
        ),
    ]
