# Generated by Django 4.2.8 on 2024-02-04 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_optionfieldvalue_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemoption',
            name='name',
        ),
        migrations.RemoveField(
            model_name='itemoption',
            name='value',
        ),
        migrations.AddField(
            model_name='itemoption',
            name='field_name',
            field=models.CharField(max_length=30, null=True, verbose_name='field name'),
        ),
        migrations.AddField(
            model_name='optionfieldvalue',
            name='item_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_option', to='menu.itemoption', verbose_name='item option'),
        ),
        migrations.AlterField(
            model_name='itemoption',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='menu.menuitem', verbose_name='menu item'),
        ),
    ]
