# Generated by Django 4.2.8 on 2024-02-04 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_remove_itemoption_name_remove_itemoption_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionfieldvalue',
            old_name='value',
            new_name='field_value',
        ),
    ]
