# Generated by Django 4.2.8 on 2024-02-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_rename_value_optionfieldvalue_field_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionFieldName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='itemoption',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='optionfieldvalue',
            name='item_option',
        ),
    ]
