# Generated by Django 4.2.8 on 2024-02-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_itemoption_alter_cartitem_unique_together_and_more'),
        ('menu', '0013_optionfieldname_remove_itemoption_menu_item_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemOption',
        ),
        migrations.DeleteModel(
            name='OptionFieldValue',
        ),
    ]
