# Generated by Django 4.2.8 on 2024-02-06 11:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_delete_itemoption_delete_optionfieldvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=30, null=True, unique=True, verbose_name='field name')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='menu.menuitem', verbose_name='menu item')),
            ],
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='value')),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('item_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_option', to='menu.menuitemoption', verbose_name='item option')),
            ],
        ),
        migrations.DeleteModel(
            name='OptionFieldName',
        ),
    ]
