# Generated by Django 4.2.8 on 2024-02-09 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_menuitemoption_optionvalue_delete_optionfieldname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemoption',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_option', to='menu.menuitem', verbose_name='menu item option'),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='item_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_value', to='menu.menuitemoption', verbose_name='option value'),
        ),
    ]
