# Generated by Django 5.0.2 on 2024-02-19 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_alter_menuitemoption_menu_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemoption',
            name='field_name',
            field=models.CharField(max_length=30, null=True, verbose_name='field name'),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='item_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_value', to='menu.menuitemoption', verbose_name='option value'),
        ),
    ]
