# Generated by Django 5.0.2 on 2024-02-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_alter_menuitemoption_field_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionvalue',
            name='value',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='value'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitemoption',
            unique_together={('menu_item', 'field_name')},
        ),
        migrations.AlterUniqueTogether(
            name='optionvalue',
            unique_together={('item_option', 'value')},
        ),
    ]
