# Generated by Django 5.0.2 on 2024-02-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_alter_optionvalue_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
