# Generated by Django 4.2.8 on 2024-01-31 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_itemoption_menu_item'),
        ('order', '0002_alter_cartitem_cart_alter_cartitem_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item_option', to='order.cartitem', verbose_name='cart_item')),
                ('item_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.itemoption', verbose_name='item_option')),
            ],
            options={
                'unique_together': {('cart_item', 'item_option')},
            },
        ),
    ]
