# Generated by Django 4.2.8 on 2024-01-31 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_itemoption_menu_item'),
        ('order', '0003_cartitemoption'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitemoption',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cartitemoption',
            name='item_option',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu.itemoption', verbose_name='item_option'),
        ),
    ]
