# Generated by Django 5.0.2 on 2024-05-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_cart_id_alter_cart_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='uuid',
        ),
    ]
