# Generated by Django 4.2.8 on 2024-01-31 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_cartitemoption_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItemOption',
        ),
    ]
