# Generated by Django 4.2.8 on 2024-01-31 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_itemoption_menu_item'),
        ('order', '0005_delete_cartitemoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='dish_option',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.itemoption', verbose_name='dish_option'),
        ),
    ]
