# Generated by Django 4.2.8 on 2024-02-04 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_rename_value_optionfieldvalue_field_value'),
        ('order', '0007_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='dish_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.itemoption', verbose_name='dish_option'),
        ),
    ]
