# Generated by Django 4.2.8 on 2024-02-05 13:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_optionfieldname_remove_itemoption_menu_item_and_more'),
        ('order', '0008_alter_cartitem_dish_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=30, null=True, unique=True, verbose_name='field name')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'dish')},
        ),
        migrations.CreateModel(
            name='OptionFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_value', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='field value')),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('item_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_option', to='order.itemoption', verbose_name='item option')),
            ],
        ),
        migrations.AddField(
            model_name='itemoption',
            name='cart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='order.cartitem', verbose_name='cart item'),
        ),
        migrations.AddField(
            model_name='itemoption',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='menu.menuitem', verbose_name='menu item'),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='dish_option',
        ),
    ]
