# Generated by Django 4.2.8 on 2024-02-09 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_cartitemoption_remove_optionfieldvalue_item_option_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cartitemoption',
            name='cart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item_option', to='order.cartitem', verbose_name='cart item'),
        ),
    ]
