# Generated by Django 4.2.8 on 2024-02-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_alter_menuitemoption_menu_item_and_more'),
        ('order', '0011_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitemoption',
            name='option_value',
        ),
        migrations.AddField(
            model_name='cartitemoption',
            name='option_value',
            field=models.ManyToManyField(related_name='option_value', to='menu.optionvalue', verbose_name='option value'),
        ),
    ]
