# Generated by Django 4.2.8 on 2024-02-10 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_alter_menuitemoption_menu_item_and_more'),
        ('order', '0012_remove_cartitemoption_option_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitemoption',
            name='option_value',
        ),
        migrations.AddField(
            model_name='cartitemoption',
            name='option_value_foreign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_value_foreign', to='menu.optionvalue', verbose_name='option value foreign'),
        ),
        migrations.AddField(
            model_name='cartitemoption',
            name='option_value_many',
            field=models.ManyToManyField(related_name='option_value_many', to='menu.optionvalue', verbose_name='option value many'),
        ),
    ]
