# Generated by Django 4.2.8 on 2024-02-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_alter_menuitemoption_menu_item_and_more'),
        ('order', '0013_remove_cartitemoption_option_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitemoption',
            name='option_value_foreign',
        ),
        migrations.RemoveField(
            model_name='cartitemoption',
            name='option_value_many',
        ),
        migrations.AddField(
            model_name='cartitemoption',
            name='option_value',
            field=models.ManyToManyField(related_name='option_value', to='menu.optionvalue', verbose_name='option value'),
        ),
    ]
