# Generated by Django 4.2.8 on 2024-02-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_alter_menuitemoption_menu_item_and_more'),
        ('order', '0014_remove_cartitemoption_option_value_foreign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='dish_option',
            field=models.ManyToManyField(related_name='dish_option', to='menu.optionvalue', verbose_name='dish option'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'dish')},
        ),
        migrations.DeleteModel(
            name='CartItemOption',
        ),
    ]
