# Generated by Django 5.0.2 on 2024-02-17 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_alter_menuitemoption_menu_item_and_more'),
        ('order', '0015_cartitem_dish_option_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item_option', to='order.cartitem', verbose_name='cart item')),
                ('option_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item_option', to='menu.optionvalue', verbose_name='option_value')),
            ],
        ),
    ]
