# Generated by Django 5.0.2 on 2024-02-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_cartitemoption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItemOption',
        ),
    ]
