# Generated by Django 5.0.2 on 2024-02-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_alter_menuitemoption_menu_item_and_more'),
        ('order', '0017_delete_cartitemoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='dish_option',
            field=models.ManyToManyField(blank=True, null=True, related_name='dish_option', to='menu.optionvalue', verbose_name='dish option'),
        ),
    ]
