# Generated by Django 5.0.2 on 2024-04-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, max_length=20, verbose_name='quantity'),
        ),
    ]
