# Generated by Django 5.0.2 on 2024-04-08 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_address_address_description_address_floor_and_more'),
        ('order', '0023_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=30, verbose_name='payment method')),
                ('total_price', models.PositiveSmallIntegerField(verbose_name='total price')),
                ('delivered', models.BooleanField(default=False, verbose_name='delivered')),
                ('ordered_date', models.DateTimeField(auto_now_add=True, verbose_name='ordered date')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='customer.address')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.cart', verbose_name='item')),
            ],
        ),
    ]
