# Generated by Django 5.0.2 on 2024-04-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.TextField(max_length=500, verbose_name='item'),
        ),
    ]
