# Generated by Django 5.0.2 on 2024-04-15 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_order_quantity_alter_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
