# Generated by Django 5.0.2 on 2024-04-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_remove_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.JSONField(),
        ),
    ]
