# Generated by Django 5.0.2 on 2024-04-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_remove_order_item_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateField(auto_now_add=True, verbose_name='ordered date'),
        ),
    ]
