# Generated by Django 5.0.2 on 2024-04-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_option',
            field=models.TextField(max_length=200, null=True, verbose_name='item option'),
        ),
    ]
