# Generated by Django 5.0.2 on 2024-04-16 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_orderitem_item_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_option',
        ),
        migrations.CreateModel(
            name='ItemOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_option', models.TextField(max_length=50, null=True, verbose_name='item option')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_option_value', to='order.orderitem')),
            ],
        ),
    ]
