# Generated by Django 5.0.2 on 2024-04-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_remove_orderitem_item_option_itemoptionvalue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemOptionValue',
            new_name='OrderItemOption',
        ),
    ]
